library(rpart)
data=read.csv("G:/R programming/Rfiles/challenger.csv")
head(data)
str(data)
index=1:nrow(data)
testindex=sample(index,trunc(length(index)/3))
train_data=sample(data[testindex,])
head(train_data)
test_data=sample(data[-testindex,])
head(test_data)
tree<-rpart(distress_ct~.,data = train_data,method = "class")
summary(tree)
plot(tree)
