data=read.csv("G:/R programming/Rfiles/challenger.csv",sep = ",",na.strings = c(""),header = TRUE)
head(data)
str(data)
library(Amelia)
missmap(data)
index=1:nrow(data)
testindex=sample(index,trunc(length(index)/3))
train_data=sample(data[testindex,])
head(train_data)
test_data=sample(data[-testindex,])
head(test_data)
model.log=glm(distress_ct~.,data=train_data,family = binomial(link = "logit"))
summary(model.log)
pred=predict(model.log,data=test_data)
pred
summary(pred)
