library(e1071)
iris=read.table("G:/R programming/Rfiles/testtxt.txt",sep = ",")
head(iris)
tail(iris)
is.na(iris)
iris<-na.omit(iris)
set.seed(125)
index<-1:nrow(iris)
testindex<-sample(index,trunc(length(index)/3))
train_iris=sample(iris[testindex,])
head(train_iris)
test_iris=sample(iris[-testindex,])
head(test_iris)

iris.model=svm(V5~.,data = train_iris)
summary(iris.model)
plot(iris)
pred<-predict(iris.model,data=test_data)
summary(pred)
pred
head(pred)
